Django/lecture3/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("meuNome", views.meuNome, name="meuNome"),
    path("<str:name>", views.greet, name="greet")
]

Django/lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('tarefas/', include("tarefas.urls")),
    path('task/', include('task.urls'))
]

Django/lecture3/tarefas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index")
]

Django/lecture3/task/urls.py
from django.urls import path
from . import views

#Define um nome para evitar namespace C.
app_name = 'tasks'

urlpatterns = [
    path("", views.index, name="index"),
    path("addTask", views.addTask, name="addTask")
]

Django/lecture3/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.


def index(request):
    return HttpResponse("Hello, world!")

def meuNome(request):
    return HttpResponse("Hello, Rodrigo!")

def greet(request, name):
    return HttpResponse(f"Hello, {name}!")

Django/lecture3/tarefas/views.py
from django.shortcuts import render
import datetime
# Create your views here.

def index(request):
    now = datetime.datetime.now()
    newyear = now.day == 1 and now.month == 1

    return render(request, "tarefas/index.html", {'newyear': newyear})

Django/lecture3/task/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django import forms
from django.urls import reverse

#Classe para os Formulários Django

class NewTaskForm(forms.Form):
    task = forms.CharField(label="Nova Tarefa")
    #priodidade = forms.IntegerField(label="Prioridade", min_value=1, max_value=10)


#------------------------------------------#
#iniciando uma Lista vazia (Aqui é o caso sem Sessões, bem simples)
#tasks = [] #Comentado pois vou implementar Sessão de usuário
#------------------------------------------#

#Criando as sessões de usuário (dentro da função Index)

def index(request):
    # Aqui eu verifico se existe alguma "tasks" na sessão deste usuário (usando os cookies dele)
    # Caso não, irei iniciar a "tasks" vazia
    if "tasks" not in request.session:
        request.session["tasks"] = []
    
    #------------------------------------------#
    #Caso antigo sem sessão
    #return render(request, 'task/index.html', {'tasks': tasks})
    #------------------------------------------#

    #Com Sessão
    return render(request, 'task/index.html', {
        "tasks": request.session["tasks"]
    })

def addTask(request):
    #Se o method de envio for POST
    if request.method == "POST":
        #Cria uma variavel e recebe tudo o que o usuário digitou
        form = NewTaskForm(request.POST)
        #Verifica se é valido
        if form.is_valid():
            #Pega os valores e armazena em taks
            task = form.cleaned_data["task"]

            #------------------------------------------#
            #Novamente forma antiga
            #Da um Append na Lista com os valores recebidos
            #task.append(task)
            #------------------------------------------#

            request.session["tasks"] += [task] #Adiciona na lista da sessão
            
            #Retorna através do HTTP para a o html que lista
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            #Não atendeu as "Regras" do servidor quando atualizamos, aqui
            #ele vai retornar o erro e o formulário
            return render(request, "task/addTask.html",{
                "form": form
            })
    # Aqui é o caso da conexão direta, somente cria o form em branco para o usuário
    return render(request, 'task/addTask.html', {
        "form": NewTaskForm()
    })
    

Django/lecture3/tarefas/templates/tarefas/index.html
{% load static %}

<html>
    <head>
        <title>Página Index</title>
        <link href="{% static 'tarefas/style.css' %}" rel="stylesheet">
    </head>
    <body>       
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {%endif%}
    </body>
</html>

Django/lecture3/task/templates/task/addTask.html
{% extends "task/layout.html" %}
   
{% block body %}
    <h1>Adicionar Tarefa</h1>
    <form action="{% url 'tasks:addTask' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">Listar Tarefas</a>
{% endblock %}

Django/lecture3/task/templates/task/index.html
{% extends "task/layout.html" %}

{% block body %}
    <ul>
        {% for task in tasks %}
            <li>{{task}}</li>
        {% empty %}
            <li>Lista Vazia</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:addTask' %}"> Adicionar Tarefa</a>
{% endblock %}

Django/lecture3/task/templates/task/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Tasks</title>
</head>
<body>
    {% block body %}

    {% endblock %}
</body>
</html>